#LAS TUPLAS SON LITAS INMUTABLES OSEA NO SE PUEDEN CAMBIAR SE CREAN CON PARENTESIS()
#DIGAMOS ESTADOS DE ESTADOS UNIDOS NADIE CAMBIA LOS ESTADOS ENTONCES NO SE PUEDEN MODIFICAR
#ACCEDO CON CORCHETES IGUAL A LAS TUPLAS
#NO PUEDO USAR VARIABLES QUE ME MODIFIQUEN COMO EXTEND O REMOVE
#LOS ALGORITMOS DE LAS LISTAS SON CERRADOS ENTONCES SON MAS FACILES
#PUEDO REPETIR LAS TUPLAS O LAS LISTAS MULT
#CONJUNTOS CON LLAVES
#LISTA CON CORCHETE
#DIFERENCIA LISTA Y CONJUNTO NO PUEDO HACER OPREACION DE CONJUNTOS, 

#9    #NUMERO DE ESTUDIANTES AL PERIODICO INGLES
#1 2 3 4 5 6 7 8 9     #ESTUDIANTES UNO A UNO DE PERIODICO INGLES
#9    #NUMERO DE ESTUDIANTES AL PERIODICO FRANCES
#10 1 2 3 11 21 55 6 8   #SUSCRITOS AL PERIODICO FRANCES






n = int(input("English newspaper: "))
lstEng = []
for i in range(n):
    lstEng.append(input())

n = int(input("French newspaper: "))
lstFrench = []
for i in range(n):
    lstFrench.append(input())
    
result = set(lstEng) - set(lstFrench)
print("Student only English newspapers:", len(result))

